name: ミッション反映
on:
  push:
    paths:
      - 'missions.json'
  workflow_dispatch:
jobs:
  send-missions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send missions to app
        run: python3 send_missions.py
